### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by khusseini** [pavelvelikhov/pythonql#13]
Hello there,

this looks like a great project. How can I set it up? I tried it using Python 3.5 (virtualenv) but the examples didn't work due to syntax errors.

Best regards

**Comment by pavelvelikhov** [comment]
Hi, did you run ‘pip install pythonql3’ ?

**Comment by khusseini** [comment]
Here is what I have so far:

```bash
virtualenv venv
. venv/bin/activate
pip install pythonql3
python
>>> result = [ select y for x in [1,2,3] let y = x**2 ]
```
The result of that is

```
  File "<stdin>", line 1
    result = [ select y for x in [1,2,3] let y = x**2 ]
                      ^
SyntaxError: invalid syntax
```

**Comment by pavelvelikhov** [comment]
Oh, yes, the way pythonql works is by running a preprocessor on a python code file.
Currently, it doesn’t work from the python interactive interpreter (we’ll build a special interactive
interpreter a bit later).


So you need to create a python code file, and put the following like on top:

#encoding: pythonql


Then, run this file through python, and it will invoke pythonql

**Comment by khusseini** [comment]
Ah I see. I thought it was that little line of code, but I tried it out before according to the readme
`#coding: pythonql` I guess that is a typo in there :)
