### ISSUE TITLE
cStringIO no longer in python3

### ISSUE THREAD

**Issue by wallflower** [pavelvelikhov/pythonql#14]
see: https://docs.python.org/3/whatsnew/3.0.html

I am using anaconda 3.6.5, and I was getting the following errors:
```
Error processing line 1 of C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\pythonql.pth:

  Traceback (most recent call last):
    File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\pythonql\codec\register.py", line 1, in <module>
      import codecs, cStringIO, encodings
  ModuleNotFoundError: No module named 'cStringIO'
```

I changed register.py line 1 from:
```
import codecs, cStringIO, encodings
```

to

```
import codecs, encodings
from io import StringIO as cStringIO
```

and things worked as normal.

I am not sure what this will do for python 2 users.

Anyway, I thought I would pass on the bug.

Thanks for your development of this so far.

**Comment by pavelvelikhov** [comment]
Seems like you have installed PythonQL for Python 2.
To install PythonQL for Python 3 there is a special command pip install pythonql3
Sorry for the confusion
