### ISSUE TITLE
PythonQL

### ISSUE THREAD

**Issue by daviwu** [pavelvelikhov/pythonql#15]
Hi, if I have a csv

```
sales
id, customer_name, month, amount
0, A, Jan, 100
1, A, Feb, 200
2, B, Jan, 300
3, C, Mar, 400
```

What PythonQL would be equivalent to the SQL below? I would like to query sales per customer per month. 
```
SELECT s.customer_name, s.month, SUM(s.amount)
FROM sales AS s
GROUP BY s.customer_name, s.month
```

**Comment by pavelvelikhov** [comment]
Here is one way to do it, i'm using pandas read_csv to make things simpler:

#coding: pythonql

import pandas as pd
from pythonql.pandas_lib import wrap_df

result = [ (name, month, sum(x.amount for x in s))
          for s in wrap_df(pd.read_csv('test.csv'))
          group by s.customer_name as name, s.month as month]

print(result)
