### ISSUE TITLE
Release a new version of PythonQL in Pypi

### ISSUE THREAD

**Issue by pavelvelikhov** [pavelvelikhov/pythonql#7]

**Comment by auvipy** [comment]
A pypi release would be really great

**Comment by pavelvelikhov** [comment]
@auvipy Hi, have been releasing regularly through Pypi for a while now

**Comment by auvipy** [comment]
Error processing line 1 of /usr/lib/python3/dist-packages/pythonql.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/site.py", line 173, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/usr/local/lib/python3.5/dist-packages/pythonql/codec/register.py", line 1, in <module>
      import codecs, cStringIO, encodings
  ImportError: No module named 'cStringIO'

**Comment by pavelvelikhov** [comment]
@auvipy Hi, it looks like you have installed the Python2 version of pythonql into Python3.
You'll need to uninstall this and run 'pip install pythonql3' or 'pip3 install pythonql3'. Sorry about this confusion, but I wasn't able to build a universal package so far

**Comment by auvipy** [comment]
sudo -H pip3 uninstall pythonql
Error processing line 1 of /usr/lib/python3/dist-packages/pythonql.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/site.py", line 173, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named 'pythonql'

Remainder of file ignored
Cannot uninstall requirement pythonql, not installed
asif@tb ~> sudo -H pip3 uninstall pythonql3
Error processing line 1 of /usr/lib/python3/dist-packages/pythonql.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.5/site.py", line 173, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named 'pythonql'

Remainder of file ignored
Cannot uninstall requirement pythonql3, not installed

**Comment by pavelvelikhov** [comment]
@auvipy Okay, the uninstall sometimes doesn't work well (because we copy the coding files pythonql.pth and it doesn't get cleaned up well).

You will have to manually remove this file:
/usr/lib/python3/dist-packages/pythonql.pth

Then it should all work fine.

**Comment by auvipy** [comment]
ok
